#include "UI/GV2LocationCompositeWidgetBases.h"
#include "UI/GV2TextWidgetBase.h"
#include "UI/GV2PortraitWidgetBase.h"
#include "UI/GV2ProgressBarWidgetBase.h"
#include "UI/GV2ImageWidgetBase.h"
#include "Components/WrapBox.h"
#include "Components/WrapBoxSlot.h"
#include "UI/GV2ButtonWidgetBase.h"
#include "UI/GV2KeyedCollection.h"

namespace { FGV2ScreenFieldDescriptor D(const TCHAR* Id, const TCHAR* Schema) { FGV2ScreenFieldDescriptor R; R.FieldId=FName(Id); R.SchemaId=Schema; R.bRequired=true; return R; } }
FGV2ScreenFieldDescriptor UGV2LocationTopBarWidgetBase::GetScreenFieldDescriptor_Implementation() const { return D(TEXT("top_bar"), TEXT("textsystem:schema.ui_field.location_top_bar.v1")); }
bool UGV2LocationTopBarWidgetBase::CanApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) const { return V.SchemaId==TEXT("textsystem:schema.ui_field.location_top_bar.v1") && DayText && LocationText && PrimaryResourceText; }
bool UGV2LocationTopBarWidgetBase::CaptureScreenField_Implementation(FGV2ScreenFieldValue& O) const { O=FGV2ScreenFieldValue::MakeLocationTopBar(TEXT("top_bar"),Applied); return true; }
bool UGV2LocationTopBarWidgetBase::ApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) { if(!CanApplyScreenField_Implementation(V)) return false; Applied=V.LocationTopBarValue; return DayText->ApplyText(Applied.Day)&&LocationText->ApplyText(Applied.Location)&&PrimaryResourceText->ApplyText(Applied.PrimaryResource); }
bool UGV2LocationTopBarWidgetBase::ResetScreenField_Implementation() { Applied={}; return true; }
FGV2ScreenFieldDescriptor UGV2LocationPlayerStatusWidgetBase::GetScreenFieldDescriptor_Implementation() const { return D(TEXT("player_status"), TEXT("textsystem:schema.ui_field.location_player_status.v1")); }
bool UGV2LocationPlayerStatusWidgetBase::CanApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) const { return V.SchemaId==TEXT("textsystem:schema.ui_field.location_player_status.v1") && PlayerNameText; }
bool UGV2LocationPlayerStatusWidgetBase::CaptureScreenField_Implementation(FGV2ScreenFieldValue& O) const { O=FGV2ScreenFieldValue::MakeLocationPlayerStatus(TEXT("player_status"),Applied); return true; }
namespace { bool ApplyIcons(UWrapBox* Container, const TArray<FString>& Ids, TMap<FName, TObjectPtr<UGV2ImageWidgetBase>>& ByKey, TSubclassOf<UGV2ImageWidgetBase> Class, UWorld* World) { if (!Container) return Ids.IsEmpty(); if (!Class || !World) return false; TArray<UGV2ImageWidgetBase*> Ordered; return FGV2KeyedCollection::Reconcile<UGV2ImageWidgetBase, FString>(Container, Ids, ByKey, [](const FString& Id){ return FName(Id); }, [World, Class](){ return CreateWidget<UGV2ImageWidgetBase>(World, Class); }, [](UGV2ImageWidgetBase& Icon, const FString& Id){ FString Error; Icon.ApplyImageResource(Id, Error); }, Ordered); } }
bool UGV2LocationPlayerStatusWidgetBase::ApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) { if(!CanApplyScreenField_Implementation(V)) return false; Applied=V.LocationPlayerStatusValue; FString E; if(!PlayerNameText->ApplyText(Applied.Name)) return false; if(Portrait && !Applied.PortraitResourceId.IsEmpty() && !Portrait->ApplyPortrait(Applied.PortraitResourceId,TEXT(""),E)) return false; if(StaminaMeter && Applied.Meters.Num()>0) StaminaMeter->ApplyProgress(Applied.Meters[0].Percent); return ApplyIcons(ItemIcons, Applied.ItemIconResourceIds, ItemWidgetsByKey, IconWidgetClass, GetWorld()) && ApplyIcons(EffectIcons, Applied.EffectIconResourceIds, EffectWidgetsByKey, IconWidgetClass, GetWorld()); }
bool UGV2LocationPlayerStatusWidgetBase::ResetScreenField_Implementation() { Applied={}; return true; }
FGV2ScreenFieldDescriptor UGV2LocationSceneWidgetBase::GetScreenFieldDescriptor_Implementation() const { return D(TEXT("scene"), TEXT("textsystem:schema.ui_field.location_scene.v1")); }
bool UGV2LocationSceneWidgetBase::CanApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) const { return V.SchemaId==TEXT("textsystem:schema.ui_field.location_scene.v1"); }
bool UGV2LocationSceneWidgetBase::CaptureScreenField_Implementation(FGV2ScreenFieldValue& O) const { O=FGV2ScreenFieldValue::MakeLocationScene(TEXT("scene"),Applied); return true; }
bool UGV2LocationSceneWidgetBase::ApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) { if(!CanApplyScreenField_Implementation(V)) return false; Applied=V.LocationSceneValue; FString E; if(SceneContextText && !Applied.ContextText.Text.IsEmpty() && !SceneContextText->ApplyText(Applied.ContextText)) return false; if(BackgroundTile && !Applied.BackgroundTileResourceId.IsEmpty() && !BackgroundTile->ApplyImageResource(Applied.BackgroundTileResourceId,E)) return false; if(Background && !Applied.BackgroundResourceId.IsEmpty() && !Background->ApplyImageResource(Applied.BackgroundResourceId,E)) return false; if(Character && Applied.CharacterResourceIds.Num()>0 && !Character->ApplyImageResource(Applied.CharacterResourceIds[0],E)) return false; return true; }
bool UGV2LocationSceneWidgetBase::ResetScreenField_Implementation() { Applied={}; return true; }

TSubclassOf<UGV2ButtonWidgetBase> UGV2LocationCommandPanelWidgetBase::ResolveButtonWidgetClass() const { return ButtonWidgetClass; }
bool UGV2LocationCommandPanelWidgetBase::CanApplyButtonModels(const TArray<FGV2ButtonViewModel>& Models) const { if (!ButtonContainer || !ResolveButtonWidgetClass()) return false; TSet<FName> Keys; for (const FGV2ButtonViewModel& Model : Models) { if (Model.Key.IsNone() || Keys.Contains(Model.Key) || !Model.Binding.IsValid()) return false; Keys.Add(Model.Key); } return true; }
bool UGV2LocationCommandPanelWidgetBase::ApplyButtonModels(const TArray<FGV2ButtonViewModel>& Models) { if (!CanApplyButtonModels(Models)) return false; TArray<UGV2ButtonWidgetBase*> Ordered; const TSubclassOf<UGV2ButtonWidgetBase> Class = ResolveButtonWidgetClass(); if (!FGV2KeyedCollection::Reconcile<UGV2ButtonWidgetBase, FGV2ButtonViewModel>(ButtonContainer, Models, ButtonsByKey, [](const FGV2ButtonViewModel& Model){ return Model.Key; }, [this, Class](){ return GetOwningPlayer() ? CreateWidget<UGV2ButtonWidgetBase>(GetOwningPlayer(), Class) : CreateWidget<UGV2ButtonWidgetBase>(GetWorld(), Class); }, [this](UGV2ButtonWidgetBase& Button, const FGV2ButtonViewModel& Model){ Button.ApplyButtonModel(Model); Button.OnBindingInvoked.AddUniqueDynamic(this, &ThisClass::HandleButtonBindingInvoked); }, Ordered)) return false; AppliedButtonModels = Models; return true; }
void UGV2LocationCommandPanelWidgetBase::HandleButtonBindingInvoked(FGV2UiBindingHandle BindingHandle, EGV2SubmitUiInteractionResult Result) { OnBindingInvoked.Broadcast(BindingHandle, Result); }
FGV2ScreenFieldDescriptor UGV2LocationCommandPanelWidgetBase::GetScreenFieldDescriptor_Implementation() const { return D(TEXT("commands"), TEXT("textsystem:schema.ui_field.location_commands.v1")); }
bool UGV2LocationCommandPanelWidgetBase::CanApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) const { return V.FieldId == TEXT("commands") && V.SchemaId == TEXT("textsystem:schema.ui_field.location_commands.v1") && CanApplyButtonModels(V.ButtonListValue); }
bool UGV2LocationCommandPanelWidgetBase::ApplyScreenField_Implementation(const FGV2ScreenFieldValue& V) { return CanApplyScreenField_Implementation(V) && ApplyButtonModels(V.ButtonListValue); }
bool UGV2LocationCommandPanelWidgetBase::CaptureScreenField_Implementation(FGV2ScreenFieldValue& O) const { O = FGV2ScreenFieldValue::MakeLocationCommands(TEXT("commands"), AppliedButtonModels); return true; }
bool UGV2LocationCommandPanelWidgetBase::ResetScreenField_Implementation() { return ApplyButtonModels({}); }
