local boundary = require("core:module.boundary.entrypoints")
local resources = require("core:module.resources.service")
local state_validator = require("core:module.runtime.state_validator")
local instance_allocator = require("core:module.runtime.instance_allocator")
local state_hasher = require("core:module.runtime.state_hasher")
local migrate = require("core:module.runtime.migrate")
local save = require("core:module.runtime.save")
local load_save = require("core:module.runtime.load")
local mutation_window = require("core:module.runtime.mutation_window")
local actor_registry = require("core:module.runtime.actor_registry")
local world = require("core:module.runtime.world")
local service_registry = require("core:module.runtime.service_registry")
local validator_registry = require("core:module.runtime.validator_registry")
local handler_registry = require("core:module.runtime.handler_registry")
local subscriber_registry = require("core:module.runtime.subscriber_registry")
local event_bus = require("core:module.runtime.event_bus")
local location_service = require("core:module.gameplay.location_service")
local gameplay_root = require("core:module.gameplay.root")
local debug_start = require("core:module.debug.start")

return {
    id = "core:module.bootstrap.main",
    boundary = boundary,
    resources = resources,
    state_validator = state_validator,
    instance_allocator = instance_allocator,
    state_hasher = state_hasher,
    migrate = migrate,
    save = save,
    load = load_save,
    mutation_window = mutation_window,
    actor_registry = actor_registry,
    world = world,
    service_registry = service_registry,
    validator_registry = validator_registry,
    handler_registry = handler_registry,
    subscriber_registry = subscriber_registry,
    event_bus = event_bus,
    location_service = location_service,
    gameplay_root = gameplay_root,
    debug_start = debug_start,
}
