local boundary = require("core:module.boundary.entrypoints")
local resources = require("core:module.resources.service")
local text = require("core:module.resources.text")
local state_validator = require("core:module.runtime.state_validator")
local instance_allocator = require("core:module.runtime.instance_allocator")
local state_hasher = require("core:module.runtime.state_hasher")
local migrate = require("core:module.runtime.migrate")
local save = require("core:module.runtime.save")
local load_save = require("core:module.runtime.load")
local mutation_window = require("core:module.runtime.mutation_window")
local portable_value = require("core:module.runtime.portable_value")
local actor_registry = require("core:module.runtime.actor_registry")
local world = require("core:module.runtime.world")
local service_registry = require("core:module.runtime.service_registry")
local action_registry = require("core:module.runtime.action_registry")
local validator_registry = require("core:module.runtime.validator_registry")
local handler_registry = require("core:module.runtime.handler_registry")
local subscriber_registry = require("core:module.runtime.subscriber_registry")
local event_bus = require("core:module.runtime.event_bus")
local entity_extension_registry = require("core:module.runtime.entity_extension_registry")
local authoring_properties = require("core:module.authoring.properties")
local authoring_tagged_ref = require("core:module.authoring.tagged_ref")
local authoring_commands = require("core:module.authoring.commands")
local authoring_presentation = require("core:module.authoring.presentation")
local authoring_field = require("core:module.authoring.field")
local authoring_context = require("core:module.authoring.context")
local presentation_source = require("core:module.runtime.presentation_source")

return {
    id = "core:module.bootstrap.main",
    boundary = boundary,
    resources = resources,
    text = text,
    state_validator = state_validator,
    instance_allocator = instance_allocator,
    state_hasher = state_hasher,
    migrate = migrate,
    save = save,
    load = load_save,
    mutation_window = mutation_window,
    portable_value = portable_value,
    actor_registry = actor_registry,
    world = world,
    service_registry = service_registry,
    action_registry = action_registry,
    validator_registry = validator_registry,
    handler_registry = handler_registry,
    subscriber_registry = subscriber_registry,
    event_bus = event_bus,
    entity_extension_registry = entity_extension_registry,
    authoring = authoring_context,
    authoring_commands = authoring_commands,
    authoring_properties = authoring_properties,
    authoring_tagged_ref = authoring_tagged_ref,
    authoring_presentation = authoring_presentation,
    authoring_field = authoring_field,
    presentation_source = presentation_source,
}
